######################################################################
# Automatically generated by qmake (3.0) Di. Dez 26 19:55:09 2017
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = stdwidgets
INCLUDEPATH += .

# Input
SOURCES += main.cpp
