######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 23 10:04:02 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
