######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 23 10:52:42 2017
######################################################################

DEFINES+=QT_NO_WARNING_OUTPUT
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
